// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace MovieAPI.Models
{
    public partial class Movie
    {
        public Movie()
        {
            MovieGenre = new HashSet<MovieGenre>();
            MoviePerson = new HashSet<MoviePerson>();
        }

        public Guid Guid { get; set; }
        public string Name { get; set; }
        public decimal? Rate { get; set; }
        public DateTime? ReleaseDate { get; set; }
        public string PosterUrl { get; set; }
        public string Description { get; set; }
        public int? Runtime { get; set; }

        public virtual ICollection<MovieGenre> MovieGenre { get; set; }
        public virtual ICollection<MoviePerson> MoviePerson { get; set; }
    }
}