// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace MovieAPI.Models
{
    public partial class MoviePerson
    {
        public Guid Guid { get; set; }
        public Guid MovieGuid { get; set; }
        public Guid PersonGuid { get; set; }
        public Guid PersonTitleGuid { get; set; }

        public virtual Movie MovieGu { get; set; }
        public virtual Person PersonGu { get; set; }
        public virtual PersonTitle PersonTitleGu { get; set; }
    }
}