// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace MovieAPI.Models
{
    public partial class Person
    {
        public Person()
        {
            MoviePerson = new HashSet<MoviePerson>();
        }

        public Guid Guid { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public DateTime? Birthdate { get; set; }
        public string Sex { get; set; }

        public virtual ICollection<MoviePerson> MoviePerson { get; set; }
    }
}